# ~/.config/kitty/kitty.conf

font_family      JetBrainsMono Nerd Font
font_size 12.0

window_padding_width 10

# WICHTIG: Pywal Colors importieren
include ~/.cache/wal/colors-kitty.conf

# Transparenz (Pywal setzt oft nur die Farben, nicht die Opacity)
background_opacity 0.85

# Editor-Integration etc.
enable_audio_bell no
copy_on_select yes




# 1. Schriftart (Wichtig für Icons!)
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

#window_margin_width 24

#background_opacity 0.88

#allow_remote_control yes
