#!/bin/bash

# Generate Pywal colors
wal -i "$1" -q

hex_to_rgb() {
    # Remove leading # if present
    hex=${1#\#}
    
    # Convert hex to rgb
    r=$(printf '0x%0.2s' "$hex")
    g=$(printf '0x%0.2s' "${hex:2}")
    b=$(printf '0x%0.2s' "${hex:4}")
    
    # Output as r,g,b
    printf "%d,%d,%d" "$r" "$g" "$b"
}

# Extract colors from Pywal's colors file
BG=$(awk 'NR==1' ~/.cache/wal/colors)
FG=$(awk 'NR==2' ~/.cache/wal/colors)
COLOR1=$(awk 'NR==3' ~/.cache/wal/colors)
COLOR2=$(awk 'NR==4' ~/.cache/wal/colors)
COLOR3=$(awk 'NR==5' ~/.cache/wal/colors)

cat > "${HOME}/.config/hypr/colors.conf" << EOF
# Auto-generated colors from pywal
\$background= rgba($(hex_to_rgb "$BG"),1.0)
\$text = rgba($(hex_to_rgb "$FG"),1.0)
\$match = rgba($(hex_to_rgb "$COLOR1"),1.0)
\$selection = rgba($(hex_to_rgb "$COLOR2"),1.0)
\$selection-text = rgba($(hex_to_rgb "$BG"),1.0)
\$border = rgba($(hex_to_rgb "$COLOR3"),1.0)
EOF

# Generate Fuzzel config
#cat <<EOF > ~/.config/fuzzel/fuzzel.ini
# fuzzel config generated by Pywal
#background = $BG
#text = $FG
#match = $COLOR1
#selection = $COLOR2
#selection-text = $BG
#border = $COLOR3
#EOF




