#!/bin/bash

# Get the pywal colors
. "${HOME}/.cache/wal/colors.sh"

# Output to hyprland colors file
cat > "${HOME}/.config/hypr/colors.conf" << EOF
# Auto-generated by pywal-colors.sh
\$color0 = 0xff${color0#\#}
\$color1 = 0xff${color1#\#}
\$color2 = 0xff${color2#\#}
\$color3 = 0xff${color3#\#}
\$color4 = 0xff${color4#\#}
\$color5 = 0xff${color5#\#}
\$color6 = 0xff${color6#\#}
\$color7 = 0xff${color7#\#}
\$color8 = 0xff${color8#\#}
\$color9 = 0xff${color9#\#}
\$color10 = 0xff${color10#\#}
\$color11 = 0xff${color11#\#}
\$color12 = 0xff${color12#\#}
\$color13 = 0xff${color13#\#}
\$color14 = 0xff${color14#\#}
\$color15 = 0xff${color15#\#}
\$foreground = 0xff${foreground#\#}
\$background = 0xff${background#\#}
EOF
